services:
  # Base service with common configuration
  base: &base
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
    secrets:
      - source: aws_credentials
        target: /run/secrets/aws_credentials 
    command: ["python", "-m", "pytest", "tests"]

  # Service for training the model
  train:
    <<: *base
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["torchrun", "--nproc_per_node=1", "gpt/train.py"]

secrets:
  aws_credentials:
    file: ~/.aws/credentials